import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

import Header from '../components/layout/Header';
import Footer from '../components/layout/Footer';
import Hero from '@/components/layout/Hero';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Hero />
        <main className="min-h-screen bg-customBackground">
          {children} {/* Dynamischer Inhalt */}
        </main>
        <Footer />
      </body>
    </html>
  );
}
